Include input source map in file coverage
istanbuljs/istanbul-lib-instrument pull request #23
Opened 2016-09-05 15:21 UTC by DatenMetzgerX

Add an option to include an input source map. The input source map
is the source map that maps the code before its instumentation back it's
original form. This is needed to support more complex setups, e.g. when
bundlers are involved. If a bundler like webpack, browserify - or you
name it - is used, then there are several, intermediate, source maps
involved. The main issue is, that the instrumented code is bundled
into a single file, and therefore a new source map is created. But the
source map of the bundled file cannot be used to remap the istanbul coverage.
Therefore, these intermediate source maps need to be stored to be available
when creating the report or remaping.

This solution is kind of hacky and should start a discussion how to solve
it best. Anyway, it fixes variouis issues that, up to now, required hacky
solutions.

refs SitePen/remap-istanbul#2

2016-09-05 15:21 UTC, yahoocla commented
Thank you for submitting this pull request, however I do not see a valid CLA on file for you. Before we can merge this request please visit https://yahoocla.herokuapp.com/ and agree to the terms. Thanks! :smile:

2016-09-05 15:21 UTC, yahoocla commented
CLA is valid!

2016-11-07 05:34 UTC, bcoe requested changes
Add some tests and let's work on landing this 👍 

If I'm reading this correctly, this doesn't change any of the existing API, just allows us to attach an additional piece of information to the coverage object?

2016-11-07 05:37 UTC, bcoe commented on src/visitor.js
> +        this.cov.inputSourceMap(inputSourceMap);
Perhaps let's only assign `this.data.inputSourceMap` if `inputSourceMap` is `undefined`? that way, for anyone not using the new API feature, the shape of the coverage object stays identical 👍

2016-11-07 07:58 UTC, DatenMetzgerX commented
Added a simple unit test that verifies if the inputSourceMap is included

> If I'm reading this correctly, this doesn't change any of the existing API, just allows us to attach an additional piece of information to the coverage object?

Thats right. If the option is not provided (and with your suggested change), the coverage object should be exactly equal to the one before.

One question is left. Should inputSourceMap be exposed (no need for .data.inputSourceMap)? Would be more consistent, however, if the coverage object is converted to json that the new property is always included....

2016-11-10 05:31 UTC, bcoe approved these changes

2016-11-10 05:33 UTC, bcoe commented on src/visitor.js
> +        if (typeof (inputSourceMap) !== "undefined") {
👍

2016-11-10 05:48 UTC, merged

2016-11-10 06:32 UTC, MichaReiser commented on src/visitor.js
> +        if (typeof (inputSourceMap) !== "undefined") {
Great, thanks!

2017-09-27 15:31 UTC, jasonwr commented
Solid work @bcoe @MichaReiser Integrating this now.